### ISSUE TITLE
UUID mismatch in Project.toml and JuliaRegistries/General Package.toml

### ISSUE THREAD

**Issue by jaakkor2** [haampie/ArnoldiMethod.jl#103]
`]add ArnoldiMethod#master` gives
```
   Updating git-repo `https://github.com/haampie/ArnoldiMethod.jl.git`
ERROR: UUID `3ad52dbc-8794-42d5-ba69-10f868172940` given by project file `C:\Users\jaakkor2\AppData\Local\Temp\jl_kECCTZ\Project.toml` does not match given UUID `ec485272-7323-5ecc-a04f-4719b315124d`
```

https://github.com/haampie/ArnoldiMethod.jl/blob/master/Project.toml#L2
has
`uuid = "3ad52dbc-8794-42d5-ba69-10f868172940"`
and
https://github.com/JuliaRegistries/General/blob/master/A/ArnoldiMethod/Package.toml#L2
has
`uuid = "ec485272-7323-5ecc-a04f-4719b315124d"`
This dates Aug 31 2018.

**Comment by haampie** [comment]
Thanks!
