### ISSUE TITLE
matrix-free example

### ISSUE THREAD

**Issue by francispoulin** [haampie/ArnoldiMethod.jl#106]
Can someone help me find an example of how to compute eigenvalues in this repo using a matrix-free approach?

**Comment by fgerick** [comment]
You can use a linear operator for your matrix free function `f!` using `LinearMaps`:
```julia
using ArnoldiMethod, LinearMaps

n = 100
A = sprandn(n,n,0.01)

f!(y,x) = mul!(y,A,x)
LO = LinearMap{ComplexF64}(f!,n)

evals, evecs = partialeigen(partialschur(LO)[1])
```

of course this example is not really matrix free ;)

**Comment by francispoulin** [comment]
Thank you @fgerick , that is most helpful!  

Even though you used a (sparse) matrix to build the function, I see how this would work in a purely matrix free world.

**Comment by francispoulin** [comment]
A small comment, for anyone who might find this.  For the above the work, we also need the libraries LinearAlgebra and SparseArrays.
```
using ArnoldiMethod, LinearMaps, SparseArrays, LinearAlgebra
```

**Comment by francispoulin** [comment]
@fgerick : another question for you or anyone else who cares to answer.  

Given that this library works for matrix-free methods, I tried using this on `CuArray`'s and it seems to work.  I have copied and pasted code from here and there so it's not clean but it seems to work.

**Comment by haampie** [comment]
Hm, it works on the gpu? I forgot/missed that. Are you sure it's not converting to float32? You might also want to look at the (colwise) norm of AQ-QR (the partial schur decomp residual)

**Comment by francispoulin** [comment]
Good question. I thought it did as it spit out an answer, but when I used nvprof to profile it I found that it fails even when I try and copy the array onto a gpu.  Error copied below.

I will try and fix this but do you think that I can use this library on gpus or is that not possible?

```
julia> # on a gpu
       d_A = CuSparseMatrixCSR(A)
==253109== NVPROF is profiling process 253109, command: julia
Missing definition of the OpenACC API routine/s in the OpenACC library linked to the application. To work around this issue either force the inclusion of all the OpenACC symbols in the binary or link the OpenACC library dynamically.
==253109== Profiling application: julia
==253109== Profiling result:
No kernels were profiled.
No API activities were profiled.
======== Error: Application returned non-zero code 12
```
